### ISSUE TITLE
Exception encountered when loading plugin: MCDiscordVerify

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [dalbodeule/MCDiscordVerify#2]
plugin does not generate configs at all, no commands available for it also
```
[18:45:29 WARN]: Exception encountered when loading plugin: MCDiscordVerify
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at space.mori.mcdiscordverify.bungee.MCDiscordVerify$Companion.setInstance(MCDiscordVerify.kt) ~[?:?]
        at space.mori.mcdiscordverify.bungee.MCDiscordVerify.onEnable(MCDiscordVerify.kt:24) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:312) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 6 more
```

**Comment by dalbodeule** [comment]
Dear TheJoshue.

Thank you for issue. This exception is problem of kotlin libraries. Minecraft isan't have kotlin lib, but This plugin is writted by kotlin. So, this plugin also have kotlin libraries.

I will solve this problem, and update plugins. Thanks.

Dalbodeule.

**Comment by dalbodeule** [comment]
[Here](https://github.com/dalbodeule/MCDiscordVerify/releases/tag/2.1.1) to new release of my plugin!
